[package]
build = "build.rs"
edition = "2021"
name = "wasmedge_runtime"
version = "0.1.0"

[dependencies]
anyhow = "*"
wasmedge-macro = "0.1"
wasmedge-sdk = "0.5"
wasmedge-sys = "0.10"
wasmedge-types = "0.3"
